name: build
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [11]
            fail-fast: true
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4
            - name: Set up JDK ${{ matrix.java }}
              uses: actions/setup-java@v3
              with:
                  distribution: 'zulu'
                  java-version: ${{ matrix.java }}
                  cache: gradle
            - name: Configure git
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "Github Actions"
            - name: Patch and build
              run: |
                  cd susvelo
                  ./sus build --jar
            - name: Upload a build artifact
              uses: actions/upload-artifact@v2.2.4
              with:
                name: susvelo JDK${{ matrix.java }}
                path: susvelo/susvelo/proxy/build/libs/*-all.jar
